name = "Polyester"
uuid = "f517fe37-dbe3-4b94-8317-1923a5111588"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.6.11"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
BitTwiddlingConvenienceFunctions = "62783981-4cbd-42fc-bca8-16325de8dc4b"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
ManualMemory = "d125e4d3-2237-4719-b19c-fa641b8a4667"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"
ThreadingUtilities = "8290d209-cae3-49c0-8002-c8c24d57dab5"

[compat]
ArrayInterface = "3.1.32, 4, 5, 6"
BitTwiddlingConvenienceFunctions = "0.1"
CPUSummary = "0.1.2 - 0.1.8, 0.1.11"
IfElse = "0.1"
ManualMemory = "0.1.3"
PolyesterWeave = "0.1"
Requires = "1"
Static = "0.3.3, 0.4, 0.5, 0.6"
StrideArraysCore = "0.2.1, 0.3"
ThreadingUtilities = "0.5"
julia = "1.5"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ForwardDiff", "Test"]
